# Generated by Django 4.2.4 on 2023-09-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGeneral', '0004_alter_informe_imagen_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='imagen',
        ),
    ]
